[package]
name = "k-means"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image_utils = { path = "../image_utils" }

image = "0.24.1"
oklab = "1.0.0"
rand = "0.8.5"
