[package]
name = "dither"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
image = "0.24.1"
lab = "0.6.0"
rand = "0.8.5"
